env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
parser: "@babel/eslint-parser"
rules: { quotes: ['error', 'single'], jsx-quotes: ['error', 'prefer-single'],
react/jsx-props-no-spreading: [0,{}], react/forbid-prop-types: 0,
react/destructuring-assignment: [1, "always", { "ignoreClassFields": true }]}
